version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: metrics_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: metrics
    volumes:
      - mongodb_data:/data/db
    networks:
      - metrics_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: metrics_rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - metrics_network

networks:
  metrics_network:
    driver: bridge

volumes:
  mongodb_data:
  rabbitmq_data:
