version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: metrics_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metrics_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: metrics_rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - metrics_network

networks:
  metrics_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
